- .gitignore
🔒 Close #3 
- gitignore setting + GoogleService.plist
- write here
- write here
- write here
- write here
> Documentation add gitignore

- RollingPaper/RollingPaper/Controllers/SignInViewController.swift
- RollingPaper/RollingPaper/Managers/FirebaseAuthManager.swift
- RollingPaper/RollingPaper/Resources/SceneDelegate.swift
- RollingPaper/RollingPaper/ViewModels/SignInViewModel.swift
- RollingPaper/RollingPaper/ViewModels/SignUpViewModel.swift
- RollingPaper/RollingPaper/Views/SignUpTextField.swift
🔒 Close #57 
- Auth Manager 싱글턴 리팩터링
- 유저 프로필 관련 함수를 해당 데이터 퍼블리셔에 값을 send하는 것으로 리팩터링
- write here
- write here
- write here
- write here
> Feature/authmanager singleton/#57

- RollingPaper/RollingPaper/Resources/SceneDelegate.swift
🔒 Close #60 
- write here
- AppDelegate의 rootView를 정상화 했습니다.
> Fix/fix AppDelegate rootView/#60

- RollingPaper/RollingPaper/Controllers/SplitViewController.swift
- RollingPaper/RollingPaper/Controllers/TemplateSelectViewController.swift
- RollingPaper/RollingPaper/Resources/SceneDelegate.swift
🔒 Close #54
- write here
- Category간의 Navigation Controller 연관성을 제거했습니다.
- Navigation Stack에 연속된 동일한 뷰가 쌓이지 않습니다.
> Fix/split view controller navigation stack bug/#54

- .github/ISSUE_TEMPLATE/design-request.md
> Docs/Add Design Issue Template/#71

- RollingPaper/RollingPaper/Info.plist
- RollingPaper/RollingPaper/Managers/DatabaseManager.swift
- RollingPaper/RollingPaper/Managers/FirebaseAuthManager.swift
- RollingPaper/RollingPaper/Managers/FirebaseStorageManager.swift
- RollingPaper/RollingPaper/Managers/FirestoreManager.swift
- RollingPaper/RollingPaper/Managers/LocalDatabaseMockManager.swift
- RollingPaper/RollingPaper/Managers/PaperModelFileManager.swift
- RollingPaper/RollingPaper/Resources/AppDelegate.swift
- RollingPaper/RollingPaper/Resources/SceneDelegate.swift
- RollingPaper/RollingPaper/ViewModels/SignUpViewModel.swift
🔒 Close #66 
- AuthManager 내 프로필 업데이트 함수를 추가했습니다
- Data 형식으로 인코딩한 이미지를 넘기기만 하면 자동으로 파이어베이스 스토리지에 업로드됩니다
- 스토리지에 업로드된 이후 자동으로 이미지 프로필을 파이어베이스 유저 데이터 / 로컬 데이터 퍼블리셔에 등록합니다
- 로그인, 로그아웃, 회원가입, 유저 정보 변경 등 이벤트에 따라 자동으로 유저 정보 패치가 발생합니다
- write here
- write here
- write here
> Feature/authmanager profile update funcs/#66

- RollingPaper/RollingPaper.xcodeproj/project.pbxproj
- RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
- RollingPaper/RollingPaper/Managers/FirebaseAuthManager.swift
- RollingPaper/RollingPaper/Managers/FirebaseStorageManager.swift
- RollingPaper/RollingPaper/ViewModels/SidebarViewModel.swift
🔒 Close #46
- write here
- 사이드바에서 간단한 유저 인포를 확인 할 수 있습니다.
- 레이아웃은 세부 단계에서 조정할 예정입니다.
- write here
- write here
> Feature/sidebar userinfo/#46

- RollingPaper/RollingPaper.xcodeproj/project.pbxproj
- RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
- RollingPaper/RollingPaper/Controllers/PaperStorageViewController.swift
- RollingPaper/RollingPaper/Controllers/PaperTemplateSelectViewController.swift
- RollingPaper/RollingPaper/Controllers/SplitViewController.swift
- RollingPaper/RollingPaper/ViewModels/PaperSettingViewModel.swift
- RollingPaper/RollingPaper/ViewModels/PaperStorageViewModel.swift
- RollingPaper/RollingPaper/ViewModels/PaperTemplateSelectViewModel.swift
🔒 Close #55 
- 페이퍼 보관함 화면이 나타나면 파이어베이스에서 페이퍼에 대한 썸네일을 다운받습니다
- 클래스 이름들 변경했습니다 - PaperTemplateViewController, PaperSettingViewController (ViewModel도 마찬가지)
- ~~사이드바에서 페이퍼 보관함을 탭할때마다 PaperStorageViewController의 viewdidload가 계속 호출됩니다. (제가 알기로는 앱 실행하고 한번만 호출되는걸로 알고있어서..)   이 부분 원인을 좀 알아봐야할듯합니다.~~ -> SplitView 살짝 만져서 해결했습니다!
> Feature/download preview/#55

- RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
- RollingPaper/RollingPaper/Models/CategoryModel.swift
🔒 Close #45
- write here
- 사이드바 선택 효과를 넣었습니다.
- 커스텀 셀을 제거했습니다. 추후 업데이트는 컬렉션 뷰로 리팩토링 예정입니다.
- 이펙트가 제대로 보이기 위해 테이블 뷰 레이아웃을 조절했습니다.
- 기존에 이펙트가 남는 버그가 해결되었습니다.
- gif 이미지가 좀 이상하게 보이는데 실제 동작은 부드럽게 잘 됩니다.
> Feature/add category selection effects/#45

- RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
- RollingPaper/RollingPaper/Controllers/PaperStorageViewController.swift
- RollingPaper/RollingPaper/Controllers/PaperTemplateSelectViewController.swift
- RollingPaper/RollingPaper/ViewModels/PaperSettingViewModel.swift
- RollingPaper/RollingPaper/ViewModels/PaperStorageViewModel.swift
🔒 #95 (완전히 다 한것은 아닙니다)
- 페이퍼 템플릿 뷰 수치 값들 한 곳에 다 모아놓고, 하이파이에 맞게 수치 조절
- 페이퍼 보관함 뷰 수치 값들 한 곳에 다 모아놓고, 임의 설정
- 배경 색깔 white -> systemBackground로 변경
- 코드 리팩터링
> Feature/match design/#95

- RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
🔒 Close #108 
- write here
- 이제 애플리케이션을 켰을때 user info를 잘 확인 할 수 있습니다.
> Fix/default user info view/#108 

- RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
- RollingPaper/RollingPaper/Controllers/PaperStorageViewController.swift
- RollingPaper/RollingPaper/Controllers/PaperTemplateSelectViewController.swift
🔒 Close #131 
- 하이파이 디자인대로 디자인 변경
- 10분 이하로 남았을 때 타이머 색깔 빨간색으로 바꾸기
- 스플릿뷰 열고닫힘에 따라 오토 레이아웃 적용
> Design/paper storage view hifi/#131

- RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
🔒 Close #119
- write here
- Hi-Fi에 맞게 레이아웃을 잡았습니다.
- write here
- 아직 StackView의 레이아웃이 불안정합니다.
- Selection Color를 Modern Cell에 맞게 맞추다 보니 Hi-Fi와 같은 색상을 선택하는데에 문제가 있었습니다. CustomCell을 이용하면 해결되는 문제이지만, 추후 CollectionView로의 리팩토링때 일괄 수정할 예정입니다.
- write here
- write here
> Design/sidebar design layout/#119

- RollingPaper/RollingPaper/Controllers/WrittenPaperViewController.swift
- RollingPaper/RollingPaper/Managers/LocalDatabaseFileManager.swift
- RollingPaper/RollingPaper/ViewModels/PaperSettingViewModel.swift
- RollingPaper/RollingPaper/ViewModels/WrittenPaperViewModel.swift
🔒 Close #126 
- 로그인 유무에 따라 공유버튼 눌렀을 때 뜨는 화면 다르게 만들기
- 페이퍼에 뜨는 카드들 컬렉션 뷰 셀 숫자 하드코딩된거 바꾸기
- 페이퍼 삭제하는 API 적용 + 삭제 조건 적용
- 타이머 적용 + 다 된 타이머 라벨 색깔 바꾸기
- write here
- write here
- write here
> Feature/add apis on written paper viewmodel/#126

- RollingPaper/RollingPaper/Controllers/PaperSettingViewController.swift
- RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
- RollingPaper/RollingPaper/Controllers/SignInViewController.swift
- RollingPaper/RollingPaper/Controllers/SplitViewController.swift
🔒 Close #141 
- write here
- TemplateView 내비게이션 갇힘 문제가 해결되었습니다.
> Fix/SplitView Controller Secondary View navigation error/#141

- RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
- RollingPaper/RollingPaper/Controllers/SplitViewController.swift
🔒 Close #163
- write here
- 백버튼 더블탭 에러를 해결했습니다.
> Fix/NavigationLogic Typing Error/#163

- RollingPaper/RollingPaper/Controllers/SidebarViewController.swift
🔒 Close #173
- write here
- 유저 이미지 포토를 정확하게 받아와서 사이드바에 띄우게 됩니다.
> Design/userinfo layout/#173

- RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
- RollingPaper/RollingPaper/Controllers/SignInViewController.swift
- RollingPaper/RollingPaper/Controllers/SignUpViewController.swift
- RollingPaper/RollingPaper/Views/SignUpTextField.swift
🔒 Close #174 
- 로그인 / 회원가입 뷰 → 모달 전환 / 네비게이션 전환
- 모달 / 네비게이션 전환 O
- 클리어 버튼 추가
- write here
- write here
- write here
- write here
> Feature/signinupview logic/#174

- RollingPaper/RollingPaper/Controllers/SettingScreenViewController.swift
🔒 Close #178
- write here
- 추후 사진 선택 기능 없앨 것
> Feature/profile authority/#178

- RollingPaper/Pods/Pods.xcodeproj/project.pbxproj
- RollingPaper/RollingPaper/Resources/DynamicLinks+Funcs.swift
- RollingPaper/RollingPaper/Resources/SceneDelegate.swift
🔒 Close #179
딥링크 송신 → 앱, 아이패드 환경까지 추가 (기존에는 데스크톱만)
딥링크 수신 → 보관함까지는 OK. 하지만 제대로 들어가지 않는다.
- write here
- write here
- write here
- write here
> Refactor/deeplink refactoring/#179

- RollingPaper/RollingPaper/Managers/FirestoreManager.swift
- RollingPaper/RollingPaper/Managers/LocalDatabaseFileManager.swift
- RollingPaper/RollingPaper/ViewModels/PaperStorageViewModel.swift
🔒 Close #194 
-  새로운 카드를 추가할 때마다 페이퍼 썸네일로 가지고 있는 카드 중 랜덤하게 골라서 설정합니다.
- 시뮬레이터에서는 url링크로부터 다운받는게 잘 안되는듯 합니다 -> 페이퍼 썸네일도 디폴트값으로 설정되고, 셀(카드)도 안보이긴하지만 실제기기에서는 잘 작동하는 것을 확인했습니다.
> Design/change paper thumbnail/#194
